server:
  port: 8088
spring:
  cloud:
    config:
      server:
        git:
          uri: https://lab.ssafy.com/s04-final/s04p31a305.git
          search-paths: configuration
          password: dkqjwl124!?
          username: xoghks11397@naver.com